version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test_script:
- dotnet test test/Hangfire.LiteDB.Test/Hangfire.LiteDB.Test.csproj --configuration Release -f netcoreapp1.1 --no-build
artifacts:
- path: .\src\Hangfire.LiteDB\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: Wrq+QibneTq9Rvutd75Y7Hvf+UcJ3K/RA/cl1Eb4ViymauThEu1/g22002Bx4MHn
  on:
    appveyor_repo_tag: true